### ISSUE TITLE
Régi, már bemergelt branchek törlése

### ISSUE THREAD

**Issue by LilikF** [Teaching-projects/SZE-MOSZE-2020-Merida_dualthrust#13]
@hegyhati 
Lehet hogy másik csapat ezt már kérdezte csak nem láttam, vagy esetleg le volt írva de elkerülte a figyelmem (akkor elnézést), de a már bemergelt brancheket törölhetjük? Van esetleg valami értelme meghagyni (mondjuk értékeléskor belenéztek majd vagy valami)?

**Comment by hegyhati** [comment]
Igen, sot. Kesobb bele tudunk nezni a history-ba, nem kell a branch. (az csak egy pointer)
