### ISSUE TITLE
Light-radius branch, compiler flagek módosítása

### ISSUE THREAD

**Issue by NemesTom** [Teaching-projects/SZE-MOSZE-2020-Merida_dualthrust#19]
@hegyhati @oliverosz 
Megakadtunk a light-radius branchen, minden kész és működik, ha a g++ -std=c++17 -g *.cpp paranccsal compileolunk, viszont ha - a még régebben elvárt - g++ -std=c++17 -g -Wall -Werror -Wextra *.cpp flageket is használjuk, akkor signed-unsigned comparison warning miatt nem tudunk compileolni. Az összehasonlítás szándékos és lekezeljük azokat az eseteket ahol baj lenne belőle. Hogy járjunk el?

Hibaüzenet:
Map.cpp: In constructor ‘Map::Map(std::string)’:
Map.cpp:53:26: error: comparison of integer expressions of different signedness: ‘std::__cxx11::basic_string<char>::size_type’ {aka ‘long unsigned int’} and ‘int’ [-Werror=sign-compare]
   53 |         if(line.length() > longest_row_size)
      |            ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
Map.cpp: In member function ‘void Map::drawMap(int, int, int) const’:
Map.cpp:96:13: error: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<std::vector<int> >::size_type’ {aka ‘long unsigned int’} [-Werror=sign-compare]
   96 |         if(i>=map.size()){
      |            ~^~~~~~~~~~~~
Map.cpp:112:22: error: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<std::vector<int> >::size_type’ {aka ‘long unsigned int’} [-Werror=sign-compare]
  112 |                 if(i < map.size()){
      |                    ~~^~~~~~~~~~~~
Map.cpp:113:26: error: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<int>::size_typ
’ {aka ‘long unsigned int’} [-Werror=sign-compare]
  113 |                     if(j < map[i].size()){
      |                        ~~^~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors

**Comment by oliverosz** [comment]
static casttal alakítsátok egyforma típusúra az összehasonlítandó értékeket

**Comment by NemesTom** [comment]
Köszönjük!
