### ISSUE TITLE
Final report

### ISSUE THREAD

**Issue by NemesTom** [Teaching-projects/SZE-MOSZE-2020-Merida_dualthrust#25]
Megvagyunk a két videóval és a reporttal is.

[Report](https://github.com/Teaching-projects/SZE-MOSZE-2020-Merida_dualthrust/blob/master/report/report.md)
[gameplay](https://github.com/Teaching-projects/SZE-MOSZE-2020-Merida_dualthrust/blob/master/videos/gameplay.mkv)
[codebasedefence](https://github.com/Teaching-projects/SZE-MOSZE-2020-Merida_dualthrust/blob/master/videos/codebasedefense.mp4)

**Comment by vizvezetek** [comment]
A féléves munkának megfelelően mindhárman megajánlott **jeles** érdemjegyben részesültök.
