### ISSUE TITLE
gh-pages branch beállításai - Doxygen 

### ISSUE THREAD

**Issue by LapatKrisz** [Teaching-projects/SZE-MOSZE-2020-Merida_dualthrust#4]
Helló! Adminisztrátori segítséget szeretnék kérni a Doxygen videóra hivatkozva, hogy a repó beállításainál a gh-pages branch-et a docs mappához rendelhessem. Köszönöm!

**Comment by hegyhati** [comment]
gh-pages/docs-ra allitottam be. A megfogalmazasodat nem teljesen ertettem. Ha ezt szeretned, akkor lezarhatod az issue-t. ha nem, akkor pls ird meg pontosabban.

**Comment by LapatKrisz** [comment]
Tökéletes, köszönöm szépen, erre gondoltam, a pontatlan fogalmazásomért elnézést kérek.

**Comment by LapatKrisz** [comment]
@hegyhati Az előző kommentem invalid, mert rosszul is adtam meg a source-ot, elnézést a bénázásért. Szóval a github pages-re szeretném deployolni a dokumentációt, és ehhez a gh-pages/root source-ra volna szükségem. Köszi:)

**Comment by hegyhati** [comment]
done.
