### ISSUE TITLE
Refactor branch GHA failel, nem tudunk compileolni. filesystem: No such file or directory

### ISSUE THREAD

**Issue by NemesTom** [Teaching-projects/SZE-MOSZE-2020-Merida_dualthrust#8]
@wajzy @hegyhati @oliverosz @vizvezetek A refactorálási feladattal zátonyra futottunk, kérhetnénk egy kis útbaigazítást? GHA-ben a gcc nem találja a filysystemet. Localban ugyanezzel a paranccsal compileol.

[GHA](https://github.com/Teaching-projects/SZE-MOSZE-2020-Merida_dualthrust/runs/1338726718?check_suite_focus=true)

Run g++ -Wall -Werror -Wextra -std=c++17 *.cpp -o a.out
main.cpp:4:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.

**Comment by oliverosz** [comment]
Máté már megválaszolta a kérdést a feladatleírás alatti [kommenteknél](https://github.com/orgs/Teaching-projects/teams/sze-mosze-2020/discussions/12/comments/13): újabb GCC verziót kell használni hozzá

**Comment by NemesTom** [comment]
Köszönöm, átsiklottunk felette valamiért, localban a gcc 9.3.0-án van. Zárom az issue-t.
